// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GAME_GAMEPACKET_H_
#define FLATBUFFERS_GENERATED_GAME_GAMEPACKET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace GamePacket {

struct LoginReqPacket;
struct LoginReqPacketBuilder;

struct LoginResPacket;
struct LoginResPacketBuilder;

struct ChatPacket;
struct ChatPacketBuilder;

struct GameMessage;
struct GameMessageBuilder;

enum PacketData : uint8_t {
  PacketData_NONE = 0,
  PacketData_LoginReqPacket = 1,
  PacketData_LoginResPacket = 2,
  PacketData_ChatPacket = 3,
  PacketData_MIN = PacketData_NONE,
  PacketData_MAX = PacketData_ChatPacket
};

inline const PacketData (&EnumValuesPacketData())[4] {
  static const PacketData values[] = {
    PacketData_NONE,
    PacketData_LoginReqPacket,
    PacketData_LoginResPacket,
    PacketData_ChatPacket
  };
  return values;
}

inline const char * const *EnumNamesPacketData() {
  static const char * const names[5] = {
    "NONE",
    "LoginReqPacket",
    "LoginResPacket",
    "ChatPacket",
    nullptr
  };
  return names;
}

inline const char *EnumNamePacketData(PacketData e) {
  if (::flatbuffers::IsOutRange(e, PacketData_NONE, PacketData_ChatPacket)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPacketData()[index];
}

template<typename T> struct PacketDataTraits {
  static const PacketData enum_value = PacketData_NONE;
};

template<> struct PacketDataTraits<GamePacket::LoginReqPacket> {
  static const PacketData enum_value = PacketData_LoginReqPacket;
};

template<> struct PacketDataTraits<GamePacket::LoginResPacket> {
  static const PacketData enum_value = PacketData_LoginResPacket;
};

template<> struct PacketDataTraits<GamePacket::ChatPacket> {
  static const PacketData enum_value = PacketData_ChatPacket;
};

template <bool B = false>
bool VerifyPacketData(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, PacketData type);
template <bool B = false>
bool VerifyPacketDataVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct LoginReqPacket FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoginReqPacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOKEN = 4
  };
  const ::flatbuffers::String *token() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TOKEN);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TOKEN) &&
           verifier.VerifyString(token()) &&
           verifier.EndTable();
  }
};

struct LoginReqPacketBuilder {
  typedef LoginReqPacket Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_token(::flatbuffers::Offset<::flatbuffers::String> token) {
    fbb_.AddOffset(LoginReqPacket::VT_TOKEN, token);
  }
  explicit LoginReqPacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoginReqPacket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoginReqPacket>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LoginReqPacket> CreateLoginReqPacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> token = 0) {
  LoginReqPacketBuilder builder_(_fbb);
  builder_.add_token(token);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LoginReqPacket> CreateLoginReqPacketDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *token = nullptr) {
  auto token__ = token ? _fbb.CreateString(token) : 0;
  return GamePacket::CreateLoginReqPacket(
      _fbb,
      token__);
}

struct LoginResPacket FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoginResPacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUCCESS = 4,
    VT_MESSAGE = 6,
    VT_MY_UID = 8
  };
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  int64_t my_uid() const {
    return GetField<int64_t>(VT_MY_UID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS, 1) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyField<int64_t>(verifier, VT_MY_UID, 8) &&
           verifier.EndTable();
  }
};

struct LoginResPacketBuilder {
  typedef LoginResPacket Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(LoginResPacket::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(LoginResPacket::VT_MESSAGE, message);
  }
  void add_my_uid(int64_t my_uid) {
    fbb_.AddElement<int64_t>(LoginResPacket::VT_MY_UID, my_uid, 0);
  }
  explicit LoginResPacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoginResPacket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoginResPacket>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LoginResPacket> CreateLoginResPacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    int64_t my_uid = 0) {
  LoginResPacketBuilder builder_(_fbb);
  builder_.add_my_uid(my_uid);
  builder_.add_message(message);
  builder_.add_success(success);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LoginResPacket> CreateLoginResPacketDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    const char *message = nullptr,
    int64_t my_uid = 0) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return GamePacket::CreateLoginResPacket(
      _fbb,
      success,
      message__,
      my_uid);
}

struct ChatPacket FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ChatPacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SENDER_ID = 4,
    VT_MESSAGE = 6,
    VT_TIMESTAMP = 8
  };
  const ::flatbuffers::String *sender_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SENDER_ID);
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  int64_t timestamp() const {
    return GetField<int64_t>(VT_TIMESTAMP, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SENDER_ID) &&
           verifier.VerifyString(sender_id()) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct ChatPacketBuilder {
  typedef ChatPacket Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_sender_id(::flatbuffers::Offset<::flatbuffers::String> sender_id) {
    fbb_.AddOffset(ChatPacket::VT_SENDER_ID, sender_id);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(ChatPacket::VT_MESSAGE, message);
  }
  void add_timestamp(int64_t timestamp) {
    fbb_.AddElement<int64_t>(ChatPacket::VT_TIMESTAMP, timestamp, 0);
  }
  explicit ChatPacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ChatPacket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ChatPacket>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ChatPacket> CreateChatPacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> sender_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    int64_t timestamp = 0) {
  ChatPacketBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_message(message);
  builder_.add_sender_id(sender_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ChatPacket> CreateChatPacketDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *sender_id = nullptr,
    const char *message = nullptr,
    int64_t timestamp = 0) {
  auto sender_id__ = sender_id ? _fbb.CreateString(sender_id) : 0;
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return GamePacket::CreateChatPacket(
      _fbb,
      sender_id__,
      message__,
      timestamp);
}

struct GameMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GameMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA_TYPE = 4,
    VT_DATA = 6
  };
  GamePacket::PacketData data_type() const {
    return static_cast<GamePacket::PacketData>(GetField<uint8_t>(VT_DATA_TYPE, 0));
  }
  const void *data() const {
    return GetPointer<const void *>(VT_DATA);
  }
  template<typename T> const T *data_as() const;
  const GamePacket::LoginReqPacket *data_as_LoginReqPacket() const {
    return data_type() == GamePacket::PacketData_LoginReqPacket ? static_cast<const GamePacket::LoginReqPacket *>(data()) : nullptr;
  }
  const GamePacket::LoginResPacket *data_as_LoginResPacket() const {
    return data_type() == GamePacket::PacketData_LoginResPacket ? static_cast<const GamePacket::LoginResPacket *>(data()) : nullptr;
  }
  const GamePacket::ChatPacket *data_as_ChatPacket() const {
    return data_type() == GamePacket::PacketData_ChatPacket ? static_cast<const GamePacket::ChatPacket *>(data()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_DATA_TYPE, 1) &&
           VerifyOffset(verifier, VT_DATA) &&
           VerifyPacketData(verifier, data(), data_type()) &&
           verifier.EndTable();
  }
};

template<> inline const GamePacket::LoginReqPacket *GameMessage::data_as<GamePacket::LoginReqPacket>() const {
  return data_as_LoginReqPacket();
}

template<> inline const GamePacket::LoginResPacket *GameMessage::data_as<GamePacket::LoginResPacket>() const {
  return data_as_LoginResPacket();
}

template<> inline const GamePacket::ChatPacket *GameMessage::data_as<GamePacket::ChatPacket>() const {
  return data_as_ChatPacket();
}

struct GameMessageBuilder {
  typedef GameMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data_type(GamePacket::PacketData data_type) {
    fbb_.AddElement<uint8_t>(GameMessage::VT_DATA_TYPE, static_cast<uint8_t>(data_type), 0);
  }
  void add_data(::flatbuffers::Offset<void> data) {
    fbb_.AddOffset(GameMessage::VT_DATA, data);
  }
  explicit GameMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GameMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GameMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GameMessage> CreateGameMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GamePacket::PacketData data_type = GamePacket::PacketData_NONE,
    ::flatbuffers::Offset<void> data = 0) {
  GameMessageBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_data_type(data_type);
  return builder_.Finish();
}

template <bool B>
inline bool VerifyPacketData(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, PacketData type) {
  switch (type) {
    case PacketData_NONE: {
      return true;
    }
    case PacketData_LoginReqPacket: {
      auto ptr = reinterpret_cast<const GamePacket::LoginReqPacket *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketData_LoginResPacket: {
      auto ptr = reinterpret_cast<const GamePacket::LoginResPacket *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketData_ChatPacket: {
      auto ptr = reinterpret_cast<const GamePacket::ChatPacket *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyPacketDataVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPacketData(
        verifier,  values->Get(i), types->GetEnum<PacketData>(i))) {
      return false;
    }
  }
  return true;
}

inline const GamePacket::GameMessage *GetGameMessage(const void *buf) {
  return ::flatbuffers::GetRoot<GamePacket::GameMessage>(buf);
}

inline const GamePacket::GameMessage *GetSizePrefixedGameMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<GamePacket::GameMessage>(buf);
}

template <bool B = false>
inline bool VerifyGameMessageBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<GamePacket::GameMessage>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedGameMessageBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<GamePacket::GameMessage>(nullptr);
}

inline void FinishGameMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GamePacket::GameMessage> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGameMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GamePacket::GameMessage> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace GamePacket

#endif  // FLATBUFFERS_GENERATED_GAME_GAMEPACKET_H_
