// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ChatPacket {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChatPacket {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChatPacket(bb:flatbuffers.ByteBuffer, obj?:ChatPacket):ChatPacket {
  return (obj || new ChatPacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChatPacket(bb:flatbuffers.ByteBuffer, obj?:ChatPacket):ChatPacket {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChatPacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

senderId():string|null
senderId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
senderId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startChatPacket(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addSenderId(builder:flatbuffers.Builder, senderIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, senderIdOffset, 0);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, messageOffset, 0);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(2, timestamp, BigInt('0'));
}

static endChatPacket(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChatPacket(builder:flatbuffers.Builder, senderIdOffset:flatbuffers.Offset, messageOffset:flatbuffers.Offset, timestamp:bigint):flatbuffers.Offset {
  ChatPacket.startChatPacket(builder);
  ChatPacket.addSenderId(builder, senderIdOffset);
  ChatPacket.addMessage(builder, messageOffset);
  ChatPacket.addTimestamp(builder, timestamp);
  return ChatPacket.endChatPacket(builder);
}
}
