// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PacketData, unionToPacketData, unionListToPacketData } from '../game-packet/packet-data';


export class GameMessage {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): GameMessage {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsGameMessage(bb: flatbuffers.ByteBuffer, obj?: GameMessage): GameMessage {
    return (obj || new GameMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsGameMessage(bb: flatbuffers.ByteBuffer, obj?: GameMessage): GameMessage {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new GameMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  dataType(): PacketData {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.readUint8(this.bb_pos + offset) : PacketData.NONE;
  }

  data<T extends flatbuffers.Table>(obj: any): any | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
  }

  static startGameMessage(builder: flatbuffers.Builder) {
    builder.startObject(2);
  }

  static addDataType(builder: flatbuffers.Builder, dataType: PacketData) {
    builder.addFieldInt8(0, dataType, PacketData.NONE);
  }

  static addData(builder: flatbuffers.Builder, dataOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, dataOffset, 0);
  }

  static endGameMessage(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static finishGameMessageBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset) {
    builder.finish(offset);
  }

  static finishSizePrefixedGameMessageBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset) {
    builder.finish(offset, undefined, true);
  }

  static createGameMessage(builder: flatbuffers.Builder, dataType: PacketData, dataOffset: flatbuffers.Offset): flatbuffers.Offset {
    GameMessage.startGameMessage(builder);
    GameMessage.addDataType(builder, dataType);
    GameMessage.addData(builder, dataOffset);
    return GameMessage.endGameMessage(builder);
  }
}
