// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class LoginResPacket {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LoginResPacket {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLoginResPacket(bb:flatbuffers.ByteBuffer, obj?:LoginResPacket):LoginResPacket {
  return (obj || new LoginResPacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLoginResPacket(bb:flatbuffers.ByteBuffer, obj?:LoginResPacket):LoginResPacket {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LoginResPacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

success():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

myUid():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startLoginResPacket(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addSuccess(builder:flatbuffers.Builder, success:boolean) {
  builder.addFieldInt8(0, +success, +false);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, messageOffset, 0);
}

static addMyUid(builder:flatbuffers.Builder, myUid:bigint) {
  builder.addFieldInt64(2, myUid, BigInt('0'));
}

static endLoginResPacket(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLoginResPacket(builder:flatbuffers.Builder, success:boolean, messageOffset:flatbuffers.Offset, myUid:bigint):flatbuffers.Offset {
  LoginResPacket.startLoginResPacket(builder);
  LoginResPacket.addSuccess(builder, success);
  LoginResPacket.addMessage(builder, messageOffset);
  LoginResPacket.addMyUid(builder, myUid);
  return LoginResPacket.endLoginResPacket(builder);
}
}
