// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';
import { PacketType } from '../game-packet/packet-type';

export class LoginPacket {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): LoginPacket {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsLoginPacket(bb: flatbuffers.ByteBuffer, obj?: LoginPacket): LoginPacket {
    return (obj || new LoginPacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsLoginPacket(bb: flatbuffers.ByteBuffer, obj?: LoginPacket): LoginPacket {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new LoginPacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  token(): string | null
  token(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  token(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
  }

  static startLoginPacket(builder: flatbuffers.Builder) {
    builder.startObject(1);
  }

  static addToken(builder: flatbuffers.Builder, tokenOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, tokenOffset, 0);
  }

  static endLoginPacket(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createLoginPacket(builder: flatbuffers.Builder, tokenOffset: flatbuffers.Offset): flatbuffers.Offset {
    LoginPacket.startLoginPacket(builder);
    LoginPacket.addToken(builder, tokenOffset);
    return LoginPacket.endLoginPacket(builder);
  }
}
