// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ChatPacket } from '../game-packet/chat-packet';
import { LoginReqPacket } from '../game-packet/login-req-packet';
import { LoginResPacket } from '../game-packet/login-res-packet';


export enum PacketData {
  NONE = 0,
  LoginReqPacket = 1,
  LoginResPacket = 2,
  ChatPacket = 3
}

export function unionToPacketData(
  type: PacketData,
  accessor: (obj: ChatPacket | LoginReqPacket | LoginResPacket) => ChatPacket | LoginReqPacket | LoginResPacket | null
): ChatPacket | LoginReqPacket | LoginResPacket | null {
  switch (PacketData[type]) {
    case 'NONE': return null;
    case 'LoginReqPacket': return accessor(new LoginReqPacket())! as LoginReqPacket;
    case 'LoginResPacket': return accessor(new LoginResPacket())! as LoginResPacket;
    case 'ChatPacket': return accessor(new ChatPacket())! as ChatPacket;
    default: return null;
  }
}

export function unionListToPacketData(
  type: PacketData,
  accessor: (index: number, obj: ChatPacket | LoginReqPacket | LoginResPacket) => ChatPacket | LoginReqPacket | LoginResPacket | null,
  index: number
): ChatPacket | LoginReqPacket | LoginResPacket | null {
  switch (PacketData[type]) {
    case 'NONE': return null;
    case 'LoginReqPacket': return accessor(index, new LoginReqPacket())! as LoginReqPacket;
    case 'LoginResPacket': return accessor(index, new LoginResPacket())! as LoginResPacket;
    case 'ChatPacket': return accessor(index, new ChatPacket())! as ChatPacket;
    default: return null;
  }
}
