// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PacketType } from '../game-packet/packet-type';


export class PacketHeader {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): PacketHeader {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsPacketHeader(bb: flatbuffers.ByteBuffer, obj?: PacketHeader): PacketHeader {
    return (obj || new PacketHeader()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsPacketHeader(bb: flatbuffers.ByteBuffer, obj?: PacketHeader): PacketHeader {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new PacketHeader()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  type(): PacketType {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.readInt8(this.bb_pos + offset) : PacketType.NONE;
  }

  size(): number {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
  }

  static startPacketHeader(builder: flatbuffers.Builder) {
    builder.startObject(2);
  }

  static addType(builder: flatbuffers.Builder, type: PacketType) {
    builder.addFieldInt8(0, type, PacketType.NONE);
  }

  static addSize(builder: flatbuffers.Builder, size: number) {
    builder.addFieldInt32(1, size, 0);
  }

  static endPacketHeader(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createPacketHeader(builder: flatbuffers.Builder, type: PacketType, size: number): flatbuffers.Offset {
    PacketHeader.startPacketHeader(builder);
    PacketHeader.addType(builder, type);
    PacketHeader.addSize(builder, size);
    return PacketHeader.endPacketHeader(builder);
  }
}
