// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum PacketType {
  NONE = 0,
  LOGIN_REQ = 1,
  LOGIN_RES = 2,
  CHAT_MSG = 3,
  ERROR = 4
}
